### PR TITLE
Docs: Add caption in captions' html examples

### PR DESCRIPTION
**Pull request by hannahiss**
Add caption in captions' html examples so that developers can see how to use it
_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Description

Add captions in html code example

### Motivation & Context

In captions' section, we have 2 examples with  caption, but no caption in the html example.

### Types of change

- Bug fix (non-breaking which fixes an issue)

### Live previews

- <https://deploy-preview-2033--boosted.netlify.app/docs/5.3/content/tables/#captions>

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [x] My change follows accessibility good practices; I have at least run axe

#### Design

- [x] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [x] My change is compatible with responsive display

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- (NA) I have added JavaScript unit tests to cover my changes
- (NA)  I have added SCSS unit tests to cover my changes

#### Documentation

- [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] My change introduces changes to the migration guide
- (NA)  My new component is added in Storybook
- (NA)  My new component is compatible with RTL
- (NA)  Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- (NA)  Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

### CODE REVIEW

**Review by MewenLeHo — COMMENTED** [review]
Good catch!

Just a question: the captions are present in Bootstrap (https://getbootstrap.com/docs/5.2/content/tables/#captions) meaning they were intentionnaly removed from Boosted. Do we know why? And when?

Because if it was trully intentional there was probably a reason to do it? (honestly I don't see any good reason to do it 🤔 )

**Comment by hannahiss** [comment]
> Just a question: the captions are present in Bootstrap (https://getbootstrap.com/docs/5.2/content/tables/#captions) meaning they were intentionnaly removed from Boosted. Do we know why? And when?
> 
> Because if it was trully intentional there was probably a reason to do it? (honestly

Good question... I've been digging: it seems it comes from #859

**Comment by hannahiss** [comment]
> > Just a question: the captions are present in Bootstrap (https://getbootstrap.com/docs/5.2/content/tables/#captions) meaning they were intentionnaly removed from Boosted. Do we know why? And when?
> > Because if it was trully intentional there was probably a reason to do it? (honestly
> 
> Good question... I've been digging: it seems it comes from #859

**Comment by hannahiss** [comment]
(answer from LM who has issues with Github access these days)
>  meaning they were intentionnaly removed from Boosted. Do we know why? And when?
Good catch Hannah, it comes from #859.

FWIW, I tried to bring much Bootstrap commits inside this PR such as the table shortcode so it had many impacts on the table.md and I missed the one here. It was surely unintentional to remove the caption code in the demo caption section so it would be great to see it back in the doc!

**Review by MewenLeHo — APPROVED** [review]
LGTM with LM's answer.

**Review by julien-deramond — APPROVED** [review]

**Pull request merged**
