### PR TITLE
fix(#1019): modify buttons icons padding

### LINKED ISSUE #1019: Icons in buttons icons should be 1px lower
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Icons in buttons icons should be 1px lower.
chrome
firefox

### Reduced test cases

The problem is present for every icon and on every browser.

It seems that a fix has been created in V4, it may be worth a try.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Boosted are you using?

v5.2.0 (current main branch)

### PR DESCRIPTION
**Pull request by MewenLeHo**
Closes #1019

### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Icons in buttons icons should be 1px lower.
chrome
firefox

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### CODE REVIEW

**Review by louismaximepiton — APPROVED** [review]
Sounds not good to me.

**Review by louismaximepiton — COMMENTED** [review]
It looks like something's wrong with that : Icons are 1px too low, on discuss.

**Comment by MewenLeHo** [comment]
> It looks like something's wrong with that : Icons are 1px too low, on discuss.

One possible way:
- keep the modification
- remove the .btn > svg {translate(1px)} rule
- replace it by adding "display: inline-flex; align-items: center;" on .btn => same result in a cleaner and more modern way to achieve it.

**Review by julien-deramond — CHANGES_REQUESTED** [review]
It doesn't work with Firefox 95.0.1 (64-bit) under Ubuntu. The icon is not centered.

Screenshot from 2022-01-07 14-06-33

But I don't understand the issue. In the issue the icon seems to be centered in the screenshot. It is not because we have 7px / 9px in the inspector that it is the reality. `transform: translateY(1px)` is not reflected in those values.

**Review by julien-deramond — APPROVED** [review]
Checked it and it works with the latest versions of:
* Ubuntu
  * Chrome
  * Firefox
* macOS
   * Chrome
   * Firefox
   * Safari

If you've tested it with Browserstack as well, I think we can merge it.

**Review by louismaximepiton — APPROVED** [review]

**Pull request merged**
