### PR TITLE
`input[type=range]` fix on Chrome

### LINKED ISSUE #1264: Range slider: no progress bar
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I can't see no progress bar on range slider

### Reduced test cases

Go on https://boosted.orange.com/docs/forms/range/.

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

5.2.0 (current_main_branch)

### PR DESCRIPTION
**Pull request by louismaximepiton**
Fixes #1264 

https://deploy-preview-1282--boosted.netlify.app/docs/5.2/forms/range/

It fixes the thumb display on Chrome and add an explaination to implement the runnable track on Chrome.

### CODE REVIEW

**Comment by julien-deramond** [comment]
CodePen rendering isn't a bit weird with the black border when we click on the slider?

Peek 2022-05-31 07-30

**Comment by julien-deramond** [comment]
Regarding the use of a CodePen I'm not against it atm but I'm afraid it would be complicated to maintain for each version.
In the documentation, we already have a "Progressive enhancement" warning callout, wouldn't be easier to maintain to explain the content of your CodePen directly in the documentation (even without showing the rendering)?

**Comment by louismaximepiton** [comment]
> Regarding the use of a CodePen I'm not against it atm but I'm afraid it would be complicated to maintain for each version. In the documentation, we already have a "Progressive enhancement" warning callout, wouldn't be easier to maintain to explain the content of your CodePen directly in the documentation (even without showing the rendering)?

You're right, during the write of the Codepen, I was asking myself on how to remember to update this Codepen, I'll implement your idea.

**Comment by julien-deramond** [comment]
@MewenLeHo This PR can be interesting for you regarding the sliders prototypes you're developing.

**Comment by ffoodd** [comment]
FWIW this example could be lighter on the JS-side by using a CSS custom property, here's [an example on CodePen](https://codepen.io/ffoodd/pen/yLoGRrx).

**Comment by louismaximepiton** [comment]
Hi @ffoodd,

Thanks for the comment, I tried to take the CodePen into account, it kindly dedupes the CSS code which is way better. Do you think it's worth to integrate the explanation in Bootstrap directly ?

**Comment by ffoodd** [comment]
You may suggest it for sure, but I dont know if it'll be merged 🙂

**Comment by julien-deramond** [comment]
Closing it. Wait for https://github.com/twbs/bootstrap/pull/37499. If accepted in Bootstrap it will be introduced in Boosted automatically. If not, we will recreate a PR here.

**Pull request closed without merging**
