### PR TITLE
Docs: Update footer in order to use the ic_Mobile_Network_Coverage icon

### PR DESCRIPTION
**Pull request by hannahiss**
_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_
 
 ### Related issues
 
 
 
 ### Description
 
Update boosted sprite svg file in order to use the ic_Mobile_Network_Coverage icon instead of ic_Signal in the footer examples: download icon from DSM, update it with svgo, replace the icon in Boosted sprite file. The alignment may appear slightly to low, but on inspection it seems better than on the old version.

New version: 
image

Old version: 
image

I also took the opportunity to update 3 other svg paths that had empty bodies (reported as a warning by the linter).
 
 ### Motivation & Context
 
 It has been seen during a design review that the icon that was used was not the good one. DSM should be updated in the same way.
 
 ### Types of change
 
 
 
 
 - Bug fix (non-breaking which fixes an issue)
 
 ### Live previews
 
 
 
 - <https://deploy-preview-2022--boosted.netlify.app/docs/5.3/components/footer/#service-bar>
 
 ### Checklist
 
 
 
 
 #### Contribution
 
 - [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
 
 #### Accessibility
 
 - [x] My change follows accessibility good practices; I have at least run axe
 
 #### Design
 
 - [x] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
 - [x] My change is compatible with responsive display
 
 #### Development
 
 - [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
 - (NA) I have added JavaScript unit tests to cover my changes
 - (NA) I have added SCSS unit tests to cover my changes
 
 #### Documentation
 
 - [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly
 
 ### Checklist (for Core Team only)
 
 - (NA) My change introduces changes to the migration guide
 - (NA) My new component is added in Storybook
 - (NA) My new component is compatible with RTL
 - (NA) Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
 - (NA) Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
 - [ ] Code review
 - [ ] Design review
 - [ ] A11y review
 
 #### After the merge
 
 - [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

### CODE REVIEW

**Review by MewenLeHo — COMMENTED** [review]
'I also took the opportunity to update 3 other svg paths that had empty bodies (reported as a warning by the linter).'
Could it be possible to add some details please? At least the names of the '3 other svg paths' + no need to do it in a destinct PR?

Do we need to add a note in the migration guide? Or is this change totally transparent to the users?

**Question for the designers:** since 'ic_Mobile_Network_Coverage' and 'ic_Signal' are really similar, is there a real need to keep the two icons or could it be possible to 'merge' them?

**Comment by hannahiss** [comment]
> 'I also took the opportunity to update 3 other svg paths that had empty bodies (reported as a warning by the linter).'
> Could it be possible to add some details please? At least the names of the '3 other svg paths' + no need to do it in a destinct PR?
I just changed the code `<path xxx></path>` (with empty body) to `<path xxx/>` (with no body) for the svgs "contact", "locate" and "protection"...

**Review by MewenLeHo — APPROVED** [review]
Ready for design review, curious to know that they will say about the two icons 🤔

**Comment by Franco-Riccitelli** [comment]
The icon looks good in the footer. No issues. Thanks.

**Review by julien-deramond — CHANGES_REQUESTED** [review]
Might be worth mentioning the fact that the icon has been modified in the migration guide, isn't it? Depending on how folks have integrated our Footer component in their project in the previous Boosted version, they won't know that they need to update it.

**Review by julien-deramond — APPROVED** [review]
Still find the rendering off because of the icon not filling the entire container, but LGTM!

**Pull request merged**
