### PR TITLE
Move table-responsive class from <table> tag to <div> tag above

### PR DESCRIPTION
**Pull request by hannahiss**
### Related issues

Linked to issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1357 and PR https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1674

### Description

`.table-responsive` class was misused on some examples: it was positioned on the `<table>` tag, whereas the documentation says to wrap the table inside a HTML tag (`<div>`) with `.table-responsive`. 

### Motivation & Context

I saw this misuse while correcting some tables row height, on rich content tables examples. 

### Types of change

- Bug fix (non-breaking which fixes an issues)

### Live previews

* https://deploy-preview-1710--boosted.netlify.app/docs/content/tables/#with-icons-or-thumbnails

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [ ] My change introduces changes to the migration guide
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by julien-deramond** [comment]
Was just looking at the overall modifications to check what's the topic of this PR. The rendering seems broken here:
Screenshot 2022-12-16 at 07 55 51
The checkboxes are "glued" to the left hand side of the table.

**Comment by julien-deramond** [comment]
There is a specific rule somewhere for the docs that can maybe cause this issue only in the docs:
```
.bd-content>.table th:first-child,
.bd-content>.table td:first-child,
.bd-content>.table-responsive .table th:first-child,
.bd-content>.table-responsive .table td:first-child {
 padding-left:0;
}
```

You can try your modification outside of the docs context. Maybe that's just the extra-css for the docs that is the issue.

**Comment by julien-deramond** [comment]
If you want to cheat a little bit, you could probably use a `.table-responsive-{breakpoint}` instead of `.table-responsive` so that it doesn't trigger the specific docs CSS 😇

**Comment by hannahiss** [comment]
It seems that this rule: 
```
.bd-content {
  > .table,
  > .table-responsive .table {
    th,
    td {
      &:first-child {
        padding-left: 0;
      }
    }
  }
}
```
changes almost all tables over documentation, except the ones in Content>Tables section, because they are all wrapped inside  `<div class="bd-example">` that breaks the rule. By moving `.table-responsive` to the div above, I reactivated the rule on the rich content tables **because they are missing `<div class="bd-example">`** (which I corrected in PR #1674)


Example from [Back To Top > Sass options](https://boosted.orange.com/docs/5.2/components/back-to-top/#sass-options): 

With the css rule:
image

Without the css rule:
image

Isn't it strange that all our tables across documentation do not respect our design specifications ?

Tables from ODS design specs:
image

Why should we keep this strange rule ?

**Comment by julien-deramond** [comment]
Since Boosted doc must respect our design guidelines as well. From what I understand, we can probably remove this rule entirely and have a slightly different display compared to Bootstrap.

**Comment by julien-deramond** [comment]
There's a rendering regression (size of checkboxes and texts) between the new version:

Screenshot 2022-12-19 at 12 58 50

And the previous one:

Screenshot 2022-12-19 at 12 59 22

**Comment by louismaximepiton** [comment]
> There's a rendering regression (size of checkboxes and texts) between the new version:
> 
> And the previous one:

The issue comes from the fact that the direct `.table` of `.bd-content` have their font-size reduced. Shall we changed it ? Otherwise a quick solution here is to wrap those with a `.bd-example`.

**Review by julien-deramond — APPROVED** [review]

**Pull request merged**
