### PR TITLE
feat(docs): enhance Algolia search results for a11y

### LINKED ISSUE #1359: Use dropdown design to implement Algolia search results in documentation

### PR DESCRIPTION
**Pull request by julien-deramond**
Fixes #1359

The goal of this PR is to improve the Algolia search results as much as possible as a quick win before that the designers have the time to provide us complete design guidelines.

Let's use our dropdown design guidelines in mind to improve the rendering.

Feel free to propose things on top of my commits to improve that.
Ping @Lausselloic as well if you have some quick wins ideas.

### Changes

- Border radius of all components inside
- Add some padding inside
- Make some links look great
- Make icons look better

### CODE REVIEW

**Comment by louismaximepiton** [comment]
Tried some things but still remains: 
* focus on links that will be handled by #1189.
* There's an overflow caused by `mark` tag (padding-y applied) that will be resolved soon in v5.

**Comment by louismaximepiton** [comment]
FWIS, the Algolia logo should stay like that according to their [DS](https://algolia.frontify.com/d/1AZwVNcFZiu7/style-guide#/basics/algolia-logo).

**Comment by julien-deramond** [comment]
> FWIS, the Algolia logo should stay like that according to their [DS](https://algolia.frontify.com/d/1AZwVNcFZiu7/style-guide#/basics/algolia-logo).

_Source: https://www.algolia.com/for-open-source/_

Screenshot from 2022-08-26 13-44-56

**Comment by julien-deramond** [comment]
Check with a11y team if we:
- should display highlighted hit terms with black background in orange or let them in white but maybe with some bold
- should let the margin/padding around the hit terms; can be difficult to read

**Comment by louismaximepiton** [comment]
The black/white background/color is the best since it has the greatest contrast. But you're right, with the font-weight, it's even more readable. However, according to a11y team, the padding helps to read the highlighted message.

**Pull request merged**
