### PR TITLE
chore: update maintainers information

### PR DESCRIPTION
**Pull request by julien-deramond**
### Description

Dropping myself from the repository 😢 

<details>
<summary>Change a CodePen: Done</summary>
⚠️ In the introduction page, we have the following:

> Get started by including Boosted's production-ready CSS and JavaScript via CDN without the need for any build steps. See it in practice with this [Boosted CodePen demo](https://codepen.io/julien-deramond/pen/WNMxywB).

It would be nice if some of you could fork this CodePen demo and change in this PR the new URL 👌 
</details>

### Types of change

- Documentation update

### Live previews

- https://deploy-preview-2798--boosted.netlify.app/docs/5.3/about/team/

### CODE REVIEW

**Review by hannahiss — CHANGES_REQUESTED** [review]
Need to add Vincent in the about>team page?

**Review by louismaximepiton — APPROVED** [review]
<details>
<summary>Looks good 😭</summary>

Sans titre
</details>

**Comment by julien-deramond** [comment]
> Need to add Vincent in the about>team page?

Hum, it's already done, isn't it?

**Comment by hannahiss** [comment]
> Need to add Vincent in the about>team page?

Sorry I misread...

**Review by hannahiss — APPROVED** [review]

**Comment by hannahiss** [comment]
I sadly approved... 😢

**Pull request merged**
