### PR TITLE
fix(#694): replace the boosted.netlify doc links with /docs/5.0

### LINKED ISSUE #694: Correct link to v5.0 docs (from 4.6)
When we are on 4.6 docs (https://boosted.orange.com/docs/4.6/getting-started/introduction/), the link pointing to v5.0 doc is the netlify one (https://v5-dev--boosted.netlify.app/docs/5.0/getting-started/introduction/)

We just need to change it for it to go to boosted.orange.com/docs/5.0

### PR DESCRIPTION
**Pull request by julien-deramond**
closes #694

### CODE REVIEW

**Comment by julien-deramond** [comment]
I've inserted the diffs for the `dist/css/*.min.css.map` files after having locally launched `npm run test`. Should I keep those modifications in this PR or not?

**Comment by ffoodd** [comment]
No, they should follow compiled files. You can't update map files without compiled files since they won't match.

**Comment by julien-deramond** [comment]
@Nurovek Could be nice to review this PR before https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/714 in order to have this modification in the v5.0.2.

**Review by Nurovek — APPROVED** [review]

**Comment by Nurovek** [comment]
Fine for me

**Pull request merged**
