### PR TITLE
Doc: URL without version

### LINKED ISSUE #1046: Redirect documentation pages to the latest version automatically
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add an alias somewhere to redirect all https://boosted.orange.com/docs/* requests to the latest version of the page.

Example: https://boosted.orange.com/docs/getting-started/introduction/ would redirect to https://boosted.orange.com/docs/5.1/getting-started/introduction/ at the moment.

Right now, we have a 404 error.

### Motivation and context

Some links to the documentation components will be added in [Orange Design System](https://system.design.orange.com). We don't want to update them for each next version of Boosted.

Note: could be done for Bootstrap as well if interesting for them. Some discussion in https://github.com/twbs/bootstrap/issues/28581.

### Related topics not to forget

- Impact on SEO
- Handle the previous versions: 5.0, 4.6, etc.

### PR DESCRIPTION
**Pull request by louismaximepiton**
Closes #1046 

I'll update 

Previews that go to the same final page : 

- https://deploy-preview-1088--boosted.netlify.app/components/ (already in)
- https://deploy-preview-1088--boosted.netlify.app/docs/components/ (added with PR)
- https://deploy-preview-1088--boosted.netlify.app/docs/5.2/components/ (already in)
- https://deploy-preview-1088--boosted.netlify.app/docs/components/accordion/ (added with PR)
- https://deploy-preview-1088--boosted.netlify.app/docs/5.2/components/accordion/ (base URL)

Same as above for a different page : 

- https://deploy-preview-1088--boosted.netlify.app/docs/extend/ (added with PR)
- https://deploy-preview-1088--boosted.netlify.app/docs/5.2/extend/ (already in)
- https://deploy-preview-1088--boosted.netlify.app/docs/5.2/extend/approach/ (base URL)

About SEO concerns : 
- [Link](https://discourse.gohugo.io/t/is-hugo-alias-a-301-redirect-does-it-affect-seo/24108) to say that it doesn't affect SEO because these links didn't exist before and it won't change the content of the main page. Edit : [Is and will not be implemented](https://github.com/gohugoio/hugo/issues/2703). BUT EDIT: See the following image and there's a 301 code.
image

- [Link](https://moz.com/learn/seo/redirection) about redirection status good for SEO or not (301 is good) and aliases do as it is a 301 redirect so fine on this side. Edit : After a curl on netlify launch a 200 code but robots noindex. One solution is to add redirects to the HTTP server [example](https://romain.therrat.fr/posts/2020/04/hugo-redirections-301/).
- [One idea to redirect 301](https://docs.netlify.com/routing/redirects/).
- [Another one](https://discourse.gohugo.io/t/how-to-return-301-moved-permanently/16734/5).

### CODE REVIEW

**Comment by julien-deramond** [comment]
FYI https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/956 has been merged so this PR will probably need an update.

**Comment by julien-deramond** [comment]
There's a conflict that needs an update.

**Comment by julien-deramond** [comment]
There is an issue with the following use case:
* http://localhost:9001/docs/5.2/getting-started/download/#source-files follows the anchor link
* http://localhost:9001/docs/getting-started/download/#source-files displays the right page but doesn't follow the anchor link

**Comment by julien-deramond** [comment]
I'm trying something with the `layout/alias.html` (really defined in our `redirect.html`) to preserve the anchors via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1088/commits/ca7554f7c80065dcc8c71d73f920c652f8da6df3. It is based on [this Hugo conversation](https://discourse.gohugo.io/t/preserve-the-some-anchor/37413).

**Review by julien-deramond — COMMENTED** [review]
> **Warning**
> Review in progress

## Anchors

There was an issue with the following use cases:
* https://deploy-preview-1088--boosted.netlify.app/docs/5.2/getting-started/download/#examples followed the anchor link
* https://deploy-preview-1088--boosted.netlify.app/docs/getting-started/download/#examples displayed the right page but didn't follow the anchor link

So I tried to modify `layout/alias.html` (really defined in `redirect.html`) to preserve the anchors via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/ca7554f7c80065dcc8c71d73f920c652f8da6df3. It is based on [this Hugo discussion](https://discourse.gohugo.io/t/preserve-the-some-anchor/37413).

## Local environment

For each page, I tried the different combinations of URLs and redirects.
The most complicated case being the following for information:
* http://localhost:9001/docs
* http://localhost:9001/getting-started
* http://localhost:9001/docs/getting-started
* ⚠️ http://localhost:9001/getting-started/introduction doesn't work but seems to be an edge case
* http://localhost:9001/docs/5.2/getting-started/introduction
* ⚠️ http://localhost:9001/getting-started/introduction/#next-steps doesn't work but seems to be an edge case
* http://localhost:9001/docs/getting-started/introduction/#next-steps
* http://localhost:9001/docs/5.2/getting-started/introduction/#next-steps

I’ve detected some errors fixed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1088/commits/2edfca3fc49aedb9f35980ee7ed9f19d07240943.

## Netlify environment

Did exactly the same tests as the previous section but with https://deploy-preview-1088--boosted.netlify.app and everything was working as expected.

## Local `gh-pages` for v5.2.1 and local environment

### Generate a fake v5.2.1

* `npm run release-version 5.2.0 5.2.1` (and fix the weird stuff in `package*.json`, `scss/**/*.scss` and `**/*.md` even if we don't care here)
* `npm run release`
* `cp -R /Users/ju/Orange-Boosted-Bootstrap/_site /Users/ju/Sites/` (`Sites` being the directory used by my Apache 2 local server)
* Go to http://localhost/~ju/_site/

### Testing

CSS is not loaded, URLs are not well linked between each other, but we know what we must test here. So it is not user-friendly but let's test it:

* http://localhost/~ju/_site/docs redirects to https://boosted.orange.com/docs/getting-started/introduction/
* http://localhost/~ju/_site/getting-started redirects to https://boosted.orange.com/docs/5.2/getting-started/introduction/
* http://localhost/~ju/_site/docs/getting-started redirects to https://boosted.orange.com/docs/5.2/getting-started/introduction/
* ⚠️ http://localhost/~ju/_site/getting-started/introduction doesn't work but seems to be an edge case
* http://localhost/~ju/_site/docs/5.2/getting-started/introduction redirects to http://localhost/~ju/_site/docs/5.2/getting-started/introduction/
* ⚠️ http://localhost/~ju/_site/getting-started/introduction/#next-steps doesn't work but seems to be an edge case
* http://localhost/~ju/_site/docs/getting-started/introduction/#next-steps redirects to https://boosted.orange.com/docs/5.2/getting-started/introduction/#next-steps
* http://localhost/~ju/_site/docs/5.2/getting-started/introduction/#next-steps works normally

## Local `gh-pages` for v5.3 and local environment

The manipulation was a bit more complicated so I'll just explain the main steps:

1. From this branch, generate a fake v5.2.1 as explained in the previous section
2. Clone the `gh-pages` branch and release the doc of this fake v5.2.1 like we'd do for a real release
3. Still from this branch, generate a fake v5.3.0 with the same content
4. Add in the temp `gh-pages` the content of this new fake version
5. Test the `gh-pages` in an Apache 2 HTTP server and check that the redirections are OK:
   * for the latest version
   * for the 5.2 version

## Final words

@louismaximepiton I'll let you check my commits and we'll proceed to the final validation and merge.

**Comment by louismaximepiton** [comment]
Looks fine to me too 🚀

**Pull request merged**
