### PR TITLE
fix(forms): vertical alignment of invalid feedback icon

### LINKED ISSUE #1716: Vertical alignment of danger icon in form validation feedback
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Not yet described in the DSM but there's an issue with the vertical alignment of danger icon in form validation feedback that shouldn't be centered but always aligned on top.

### Reduced test cases

Just press "Submit form" in https://boosted.orange.com/docs/5.2/forms/validation/#custom-styles and check "State" error message.

Screenshot 2022-12-19 at 09 31 19

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Boosted are you using?

v5.2

### PR DESCRIPTION
**Pull request by julien-deramond**
### Related issues

Closes #1716 

### Description

This PR removes the centered alignment of the invalid feedback icon and adds a 1px margin in order to have a better rendering.
Having more pixels as top margin moves the feedback message to the bottom which is not OK.

### Motivation & Context

We don't want the invalid feedback icon to be centered

### Types of change

- Bug fix (non-breaking which fixes an issue)

### Live previews

* https://deploy-preview-1719--boosted.netlify.app/docs/forms/validation/#custom-styles

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] All new and existing tests passed

### CODE REVIEW

**Review by louismaximepiton — COMMENTED** [review]
Since we change this, do you think that we should change the icon in order to use the one provided by Solaris ? If yes, we might not need the margin-top.

**Comment by julien-deramond** [comment]
Tried it quickly but:
* The corresponding SVG in Solaris icons is heavier than the previous one
* The corresponding SVG in Solaris has white spaces and since this icon is not used only for invalid feedback, it has other issues for alerts for example where the default rendering would be:

Screenshot 2022-12-20 at 09 27 22

I'd say that this modification is not mandatory in this PR and should be tackled as a topic on its own.

**Review by louismaximepiton — APPROVED** [review]
Let's go this way if the design is fine with this PR !

**Comment by Franco-Riccitelli** [comment]
**Design review of vertical alignment of invalid feedback icon** 

The alignment looks good. 
When the error message wraps onto two lines, the icon remains aligned to the top line of text, so all good.

**Pull request merged**
