### PR TITLE
fix(migration): use the name 'Footer' instead of 'Orange Footer'

### PR DESCRIPTION
**Pull request by julien-deramond**
### Description
 
 This PR suggests talking about "Footer" instead of "Orange Footer" in the migration guide because "Footer" is the name of this component.
 
 ### Motivation & Context
 
 Consistency and readability.
 
 ### Types of change
 
 - Bug fix (non-breaking which fixes an issue)
 
 ### Live previews
 
 - <https://deploy-preview-2042--boosted.netlify.app/>
 
 ### Checklist
 
 #### Contribution
 
 - [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
 
 #### (N/A) Accessibility
 #### (N/A) Design
 
 #### (N/A) Development
 
 #### Documentation
 
 - [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly
 
 ### Checklist (for Core Team only)
 
 - [x] My change introduces changes to the migration guide
 - (N/A) My new component is added in Storybook
 - (N/A) My new component is compatible with RTL
 - (N/A) Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
 - (N/A) Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
 
 #### After the merge
 
 - (N/A) Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

### CODE REVIEW

**Review by MewenLeHo — COMMENTED** [review]
Any need to change it in the changelog.md : 'add footers example while waiting for Orange footer component' (line 207)?

**Comment by julien-deramond** [comment]
> Any need to change it in the changelog.md : 'add footers example while waiting for Orange footer component' (line 207)?

I don't think so, it is generated automatically from the commit messages

**Comment by MewenLeHo** [comment]
> > Any need to change it in the changelog.md : 'add footers example while waiting for Orange footer component' (line 207)?
> 
> I don't think so, it is generated automatically from the commit messages

OK, so good for me.

**Review by MewenLeHo — APPROVED** [review]
🚀

**Pull request merged**
