### PR TITLE
Fix pa11y-ci execution with GitHub Actions

### PR DESCRIPTION
**Pull request by julien-deramond**
Linked to https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/681: try another approach.

Seen in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/runs/915421602:

Capture d’écran 2021-06-08 à 08 02 53

### CODE REVIEW

**Comment by julien-deramond** [comment]
Same results but with even more timeouts

Capture d’écran 2021-06-08 à 08 27 47

I'm gonna try to reduce drastically the timeout configuration just to see what the result is

**Comment by julien-deramond** [comment]
Tried it just to be sure (but not working obviously):
- Bump pa11y-ci 2.4.0 to 2.4.1
- Force pa11y dependency to 6.0.0 instead of 5.3.0

**Comment by julien-deramond** [comment]
Got an interesting thing about this problem.
https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/e9b4254c0fafc3a8631fc64c62ecab1f557e00c0/stories/create-stories-from-doc.js in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/565 randomly crashes with the following error:

```
Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/ExecutionContext.js:167:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext._evaluateInternal (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/ExecutionContext.js:120:56)
    at async ExecutionContext.evaluate (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async /Users/ju/Orange-Boosted-Bootstrap/stories/create-stories-from-doc.js:69:17
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/ju/Orange-Boosted-Bootstrap/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/ju/Orange-Boosted-Bootstrap/stories/create-stories-from-doc.js:69:28
```

ℹ️ It is always after trying to parse the last `.bd-example` of Navbar documentation page.

This error is linked to the pa11y problem because we use Puppeteer in this JavaScript file; which comes from the pa11y dependency!

**Review by Lausselloic — APPROVED** [review]
🎉 good job!

**Pull request merged**
