### PR TITLE
Borders: fix Email address border color in the Color section example

### PR DESCRIPTION
**Pull request by isabellechanclou**
_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_
 
 ### Related issues
 
 #2062
 #2063
 
 ### Description
 
 After a design review of all the Borders variants, the purpose of this PR is to fix the design of some variants in order to make them aligned on the Orange design specifications and to add design callout messages before the variants that should not be used because not suitable in Orange design system.
 
 ### Motivation & Context
 
 The goal here is to offer in Boosted more guidance on what can be used or not in Orange apps and to reduce discrepancies between Boosted documentation and the Orange design system one.
 
 ### Types of change
 
 
 
 
 - [x] Bug fix (non-breaking which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - (NA) Refactoring (non-breaking change)
 - (NA) Breaking change (fix or feature that would change existing functionality)
 
 ### Live previews
 
 - <https://deploy-preview-2065--boosted.netlify.app/docs/utilities/borders>
 
 ### Checklist
 
 #### Contribution
 
 - [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
 
 #### Accessibility
 
 - [x] My change follows accessibility good practices; I have at least run axe
 
 #### Design
 
 - [x] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
 - [x] My change is compatible with responsive display
 
 #### Development
 
 - [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
 - (NA) I have added JavaScript unit tests to cover my changes
 - (NA) I have added SCSS unit tests to cover my changes
 
 #### Documentation
 
 - [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly
 
 ### Checklist (for Core Team only)
 
 - (NA) My change introduces changes to the migration guide
 - (NA) My new component is added in Storybook
 - (NA) My new component is compatible with RTL
 - (NA) Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
 - (NA) Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
 - [x] Code review
 - (NA) Design review
 - (NA) A11y review
 
 #### After the merge
 
 - (NA) Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

### CODE REVIEW

**Review by louismaximepiton — APPROVED** [review]
I feel like it doesn't add too much maintenance and if it can avoid a callout I'm in. 

However, I feel like these example aren't there to be branded (even on Bootstrap side) but they're here for comprehension. I'll approve this since it doesn't block any sense to me.

**Comment by julien-deramond** [comment]
> It won't avoid a design callout message for this section, for the 2nd and 3rd example shouldn't be used from the Orange designers' point of view.

If we already have/plan a callout for 2 out of 3 examples in this section. It's not easier to explain that the whole section is for customization only and shouldn't be used as-is, instead of using a color that should never be used by developers manually? If find it more confusing.

**Comment by julien-deramond** [comment]
@isabellechanclou This PR can be closed isn't it? It's probably superseded by #2064 which will include a callout for this section instead of modifying the rendering from Bootstrap.

**Comment by isabellechanclou** [comment]
> @isabellechanclou This PR can be closed isn't it? It's probably superseded by #2064 which will include a callout for this section instead of modifying the rendering from Bootstrap.

You're totally right! Let's close this one.

**Pull request closed without merging**
