### PR TITLE
Enhance GitHub workflows (handle Dependabot, etc.)

### LINKED ISSUE #847: GitHub Workflows - Ignoring Dependabot branches
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Observed while merging Bootstrap commits (e.g. https://github.com/twbs/bootstrap/commit/78e9b402df84042920d9f2a61e86fc3bb0b4dcea).
Our GitHub workflows approach is slightly different concerning Dependabot.

This issue is a study to see if we shouldn't use the same approach than Bootstrap (use `branches-ignore` for example).
Well verify if it has an impact on Dependabot branches / PRs because it doesn't seem to work as expected right now with the `!dependabot/**` rules. 

### Motivation and context

Resynchronizing our GitHub workflows with Bootstrap for `v4-dev` and `main` branches.

### PR DESCRIPTION
**Pull request by louismaximepiton**
Fixes #847

**Features** : 
- Keep the Boosted method with the skip labels (But should be less used now).
- Remove dependabot branches by the actor dependabot itself.
- Move the checks at a job level.
- Dependabot ci could be triggered by any user action on the PR (adding a label).
- Removed the optimize dupe workflow on Boosted.

**Note** : 
- top-level triggers such as `push` or `pull_request` are in a OR statement. That means that either will trigger action. On the other side (and I'm sorry, I misunderstood this at first) the `branches`, `tags` or `paths` are in a AND statement. That means that a worflow will trigger if the changes are in a specified path AND on a specified branch. ([link](https://stackoverflow.com/a/63461325))
- The pull_request trigger branches is the base branch, so that's why former workflow was not ignoring it.
- The different types of pull_requests are [here](https://frontside.com/blog/2020-05-26-github-actions-pull_request/#:~:text=When%20a%20Github%20Actions%20workflow,opened%20%2C%20synchronize%20%2C%20and%20reopened%20.).
- Doesn't cause any issue atm but workflow-dispatch could have issues in the future, triggering the workflow manually with the skip:ci label activatede. (https://github.com/actions/runner/issues/2005)

### CODE REVIEW

**Comment by julien-deramond** [comment]
@louismaximepiton Apparently Bootstrap is working on this topic as well via https://github.com/twbs/bootstrap/pull/35574. Maybe to compare with what you've done so far.

**Comment by julien-deramond** [comment]
@louismaximepiton Since we're waiting to see what Bootstrap will do with Dependabot, is it possible to extract in an another PR your work on Percy (Browserstack) to run it automatically for _main_ && _v4-dev_ and manually for pushes and PRs? IMO it could be reviewed/merged independently.

**Comment by XhmikosR** [comment]
What's the issue with dependabot exactly? Trying to understand if we are missing something upstream.

I still need some help with BrowserStack and PRs, but other than the https://github.com/twbs/bootstrap/pull/35574 is ready to be merged.

**Comment by julien-deramond** [comment]
> What's the issue with dependabot exactly? Trying to understand if we are missing something upstream.
> 
> I still need some help with BrowserStack and PRs, but other than the [twbs/bootstrap#35574](https://github.com/twbs/bootstrap/pull/35574) is ready to be merged.

@XhmikosR We are still discussing it but we plan to do something like that:
* Basically it is very handy to know when the dependencies need to be updated but we want to stop launching the jobs automatically from Dependabot PRs because:
  * Most of the time we are waiting for you (Bootstrap) to update the dependencies to avoid conflicts
  * For our unique dependencies like pa11y-ci (and some others) I still need to check it manually (I never merge directly from the Dependabot PRs or rarely)
  * It slows down everything when it re-runs jobs while pushing real PRs or branches in the meantime
  * We have a limited amount of Browserstack / Percy runs and snapshots each month
* Run manually Percy when needed (and maybe Browserstack as well) just before merging a PR
* Run automatically Percy and Browserstack only for the _main_ branch (and maybe _v4-dev_)

We also have `skip:browserstack`, `skip:ci` etc. labels to avoid some actions to be run but it is not really automatic and not enough.  We also thought using our `skip:ci` label on all Dependabot PRs (a bit uglier than to tackle the real problem :p)

**Comment by julien-deramond** [comment]
This PR needs a rebase after the merge of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1004

**Comment by julien-deramond** [comment]
@louismaximepiton Is this PR still fixing the issue and up to date? Can it be reviewed?

**Review by julien-deramond — APPROVED** [review]
Modifications seems logical. I won't try all the use cases myself. Trust you on this. Let's merge and see if it works as expected. 🚀 🤖

**Pull request merged**
