### PR TITLE
Fix languages buttons accessible names

### PR DESCRIPTION
**Pull request by MewenLeHo**
### Description

Simple accessibility fix.

### Motivation & Context

The name of the buttons must be included in their accessible names.
See [Success Criterion 2.5.3 Label in Name](https://www.w3.org/TR/WCAG21/#label-in-name) for more details.

### Types of change

- Bug fix (non-breaking which fixes an issues)

### Live previews

* [https://deploy-preview-1629--boosted.netlify.app/docs/5.2/components/orange-navbar/#with-additional-navbar](https://deploy-preview-1629--boosted.netlify.app/docs/5.2/components/orange-navbar/#with-additional-navbar)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] My change introduces changes to the migration guide
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by julien-deramond** [comment]
Haven't reviewed the PR but I'm wondering whether we should mention it into the migration guide or not. I'd say yes but not 100% sure neither :)

**Comment by MewenLeHo** [comment]
> Haven't reviewed the PR but I'm wondering whether we should mention it into the migration guide or not. I'd say yes but not 100% sure neither :)

Same here, I was waiting for your opinion ;)

**Comment by julien-deramond** [comment]
Tried something in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1629/commits/44298a705bc42846c878ffa35589168f9db7f757. Let me know what you think.

**Comment by MewenLeHo** [comment]
> Tried something in [44298a7](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/44298a705bc42846c878ffa35589168f9db7f757). Let me know what you think.

Looks good. I am just wondering if we should add why it could be useful (because for accessibility purposes, the visible name must be included in the accessible name)? I don't know if the migration guide is the right place to explain that?

**Review by julien-deramond — APPROVED** [review]

**Pull request merged**
