### PR TITLE
Add story button component

### PR DESCRIPTION
**Pull request by MewenLeHo**
### Related issues

Part of #1761 

### Description

Add story button componenent

### Motivation & Context

New component based on UI Kit v5.

### Types of change

- New feature (non-breaking change which adds functionality)

### Live previews

[https://deploy-preview-1816--boosted.netlify.app/docs/5.3/components/buttons/#story-button](https://deploy-preview-1816--boosted.netlify.app/docs/5.3/components/buttons/#story-button
)
and don't forget: [https://deploy-preview-1816--boosted.netlify.app/docs/5.3/components/buttons/#dark-variant](https://deploy-preview-1816--boosted.netlify.app/docs/5.3/components/buttons/#dark-variant)
#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Accessibility

- [x] My change follows accessibility good practices; I have at least run axe

#### Design

- [x] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [x] My change is compatible with responsive display

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- (NA) I have added JavaScript unit tests to cover my changes

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [x] My change introduces changes to the migration guide
- [ ] My new component is added in Storybook
- [x] My new component is compatible with RTL
- [x] Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- [x] Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- [ ] Code review
- [ ] Design review
- [x] A11y review

#### After the merge

- [ ] Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

### CODE REVIEW

**Comment by julien-deramond** [comment]
I know this is a draft PR but just a question here being off for few weeks. There's only one size? What about smaller screens?

**Comment by MewenLeHo** [comment]
> I know this is a draft PR but just a question here being off for few weeks. There's only one size? What about smaller screens?

There is indeed no small size variant in the UI Kit V5 at the moment.
I asked for it at the last specs meeting and designers answered that the thumbnail displayed in the link need to be big enough to be seen so they don't plan to make a smaller version.

**Comment by Aniort** [comment]
a11y ok

**Comment by MewenLeHo** [comment]
Reminder: don't forget to add some lines to introduce this new type of button in documentation. But we need to figure out first  what it can be used for.

**Comment by MewenLeHo** [comment]
After last specs meeting with the designers, we agreed that:

- [ ] a small size variant will be needed
- [ ] we need to define exactly the UX part of this component 
- [ ] we must define if we keep it like it is or create a 'navigation' section in the documentation for story (and social ?) button(s) or even if it should be a new component by itself.

**Comment by julien-deramond** [comment]
Specifications are not complete. I'm closing this PR and mentioning it as a reference in the corresponding issue so that we can maybe start from it when it will be ready to develop. Please don't delete the branch.

**Pull request closed without merging**
