### PR TITLE
Fix tooltips and arrows positions

### PR DESCRIPTION
**Pull request by MewenLeHo**
### Related issues

Closes [#1594 ](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1594)

### Description

Change tooltips and related arrows positions depending on positions.

### Motivation & Context

Changes needed to respect Orange Design System specifications.

### Types of change

- Bug fix (non-breaking which fixes an issues)

### Live previews

* https://deploy-preview-1689--boosted.netlify.app/docs/5.2/components/tooltips/#directions

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] My change introduces changes to the migration guide
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Review by julien-deramond — CHANGES_REQUESTED** [review]
The change doesn't seem to be applied to popovers. And IMO it should.
Before doing the code review for this one (since it is rather simple in terms of code review), could you please check with the designers before if the value used (and the rendering) is OK so we have their approval?

**Comment by louismaximepiton** [comment]
Just leaving here another way to fix the issue, haven't had the time to check if this could fit the need: `data-bs-offset="0,10"`

**Comment by MewenLeHo** [comment]
I received the answer from the designers, this change must also affect popovers.

**Comment by Franco-Riccitelli** [comment]
Hi, here is my feedback on the Tooltip and Popover pointer spacing.

**Tooltip**
All look good except for the example **Tooltip with HTML**. This is slightly too close to the button. Try moving 2px.

**Popover**
The size of the pointer on Popovers is slightly larger than for Tooltips as Popovers are generally bigger.
The "point" of the pointer is still 5px away from the item it is pointing to (same as Tooltips), but the pointer height is 10px (see attached).

Popover-Spacing

**Comment by MewenLeHo** [comment]
**Tooltips:** ok

**Popovers:** in **Bootstrap**, popovers arrows are made of two half-sized arrows to make it looks like a white arrow with a grey border:

screenshot-getbootstrap com-2022 12 23-11_22_13

It's possible to resolve this PR easily by removing one of this 'half-arrow' and make the second one full size but we currently have a design issue about going tward a similar design, I even made a prototype about it.

I think we should decide what to do with this prototype and update our code accordingly. Then we will decide how to handle this PR.

**Comment by MewenLeHo** [comment]
Closed because of a change in specifications.
I wil start a new one from scratch with the correct informations.

**Pull request closed without merging**
