### PR TITLE
HTML semantic of dropdown menu

### PR DESCRIPTION
**Pull request by MewenLeHo**
Closes [#1372](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1372)

### CODE REVIEW

**Comment by julien-deramond** [comment]
Just a question. It is not a duplicate of what can be found in https://boosted.orange.com/docs/5.2/components/dropdowns/#menu-items?

**Comment by MewenLeHo** [comment]
> Just a question. It is not a duplicate of what can be found in https://boosted.orange.com/docs/5.2/components/dropdowns/#menu-items?

You are totally right. 

@isabellechanclou: what's your opinion? Should we close this PR? Is the actual version ok?

**Comment by julien-deramond** [comment]
See https://github.com/twbs/bootstrap/pull/37432

**Comment by julien-deramond** [comment]
> See [twbs/bootstrap#37432](https://github.com/twbs/bootstrap/pull/37432)

This modification has been merged. Is this PR still relevant @MewenLeHo?

**Comment by MewenLeHo** [comment]
> > See [twbs/bootstrap#37432](https://github.com/twbs/bootstrap/pull/37432)
> 
> This modification has been merged. Is this PR still relevant @MewenLeHo?

No, for me we can close this PR.

**Pull request closed without merging**
