### PR TITLE
Fixing buttons in tac

### LINKED ISSUE #1202: Color of tarteaucitronjs's (cookies manager) buttons are not correct on interactive states
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the banner and modal (Cookies management panel) displayed by tarteacitronjs when there is no cookie, the color of the buttons have to be changed to respect ODS. Note that depending on their place, they are on white or dark background and that the colors on interactive behavior are not the same.

**In the banner**:
image
- Button "OK, accept all" : focus and press states to be corrected
- Button "Deny all cookies" : focus and press states to be corrected
- Button "Personalize" : hover, focus and press states to be corrected
Refer to https://system.design.orange.com/0c1af118d/p/278ebc-standard-buttons/b/539dce/i/66611052

**In the modal (Cookies management panel)**:
image
The "Allow all cookies" (green) button and "Deny all cookies" (orange) button don't have the right background color on hover, press and focus. For the right ones, refer to https://system.design.orange.com/0c1af118d/p/278ebc-standard-buttons/b/539dce/i/66611053

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Boosted are you using?

v5.1

### PR DESCRIPTION
**Pull request by louismaximepiton**
Closes #1202.

~~Does it need a backport to v4 ?~~

To access the Panel, go on the netlify preview, open the console and several commands can be used to check : 
- `tarteaucitron.userInterface.openAlert()`
- `tarteaucitron.userInterface.openPanel()`
- `tarteaucitron.userInterface.closeAlert()`
- `tarteaucitron.userInterface.closePanel()`

⚠️ Buttons functionnality seems to be broken on netlify ⚠️

### CODE REVIEW

**Comment by julien-deramond** [comment]
> Does it need a backport to v4 ?

I'm not sure. You can try to open the cookies management panel from the v4 documentation to see if your fix is visible. If so, no need to backport it to v4.

**Comment by louismaximepiton** [comment]
Actually, these buttons seems to appear correctly, but the close and API's ones are weird to me. However, it hasn't been raised atm so I think we can keep them as they are.

**Comment by MewenLeHo** [comment]
I still have this weird javascript error we talked about. Did you have time to investigate?

**Comment by louismaximepiton** [comment]
I still have this weird behavior too on Netlify but on localhost I don't, so I guess that comes from Netlify itself and not from the cookie panel but I might be wrong.

**Pull request merged**
