### PR TITLE
Chore/merge main@bdfb4cc

### PR DESCRIPTION
**Pull request by julien-deramond**
Get Bootstrap commits from 94c80ff613dce6620591acd7f9930ce8f40c5ed0 (Sept. 7) to bdfb4cc54d29c0c7bcd7944d3c8de2e1cd41bb6c (Sept. 15).

Dear reviewer, please pay attention to https://github.com/twbs/bootstrap/commit/94c80ff613dce6620591acd7f9930ce8f40c5ed0 which had some impacts on Boosted (-> https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/807/commits/d85ae3b68edbdbf169ef502fe52e74d70c5ffb18)

### CODE REVIEW

**Comment by julien-deramond** [comment]
Bootstrap doesn't run pa11y yet. So I have to dig into the following report: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/suites/3813666741/artifacts/94282101

**Comment by julien-deramond** [comment]
pa11y is now happy but linkinator is not:
```
[...]
"file:/home/runner/work/Orange-Boosted-Bootstrap/Orange-Boosted-Bootstrap/_site/docs/5.1/forms/checks-radios/index.html":561.3-561.137: error: Attribute "aria-checked" not allowed on element "input" at this point.
"file:/home/runner/work/Orange-Boosted-Bootstrap/Orange-Boosted-Bootstrap/_site/docs/5.1/forms/checks-radios/index.html":561.3-561.137: info warning: The "aria-checked" attribute should not be used on an "input" element which has a "type" attribute whose value is "checkbox".
```

**Comment by julien-deramond** [comment]
Got a discussion with the Orange a11y community and it seems that `aria-checked` is useful with a switch role (source: https://www.w3.org/TR/wai-aria-practices-1.1/#naming_with_aria-labelledby). So it may be rather a problem with Axe. And so I've added a specific rule for pa11y analysis to avoid checking `.form-check.form-switch` content.

**Comment by julien-deramond** [comment]
We begin to have several things ignored by pa11y (see `"hideElements": ".bd-search, [id*='tarteaucitron'], #TableOfContents, .text-primary, .navbar-light .navbar-brand, .accordion-button:not(.collapsed), .active, [aria-current], select:disabled, [disabled] label, [disabled] + label, .modal, .bd-example nav, .badge.rounded-pill.bg-info.text-white, .exclude-from-pa11y-analysis, a.disabled, .form-check.form-switch",`). Maybe it would be interesting to write somewhere (Wiki?) what each rule fixes?

**Review by Nurovek — APPROVED** [review]
Any reason on why Bootstrap chose to be more explicit with parameters in functions (e -> event) ?

Other than that, I've checked behaviours for components that are modified and it seems ok for me.

**Comment by julien-deramond** [comment]
> Any reason on why Bootstrap chose to be more explicit with parameters in functions (e -> event) ?

Probably just for readability.

**Pull request merged**
