### PR TITLE
Valid icon on select

### LINKED ISSUE #1342: Validation "OK" Check is missing for Select Tag
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

Using Boosted 5.1 VS. Bootstrap 5.1, validation check icon is missing for boosted select HTML tag.

### Reduced test cases

To avoid integration issues, this bug is reproducible on Boosted/Boostrap demo sites.
https://boosted.orange.com/docs/5.1/forms/validation/
https://getbootstrap.com/docs/5.1/forms/validation

bootstrap-valid-OK
bootsted-valid-KO
/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

5.1

### PR DESCRIPTION
**Pull request by louismaximepiton**
Fixes #1342 

Actually wondering if we need to continue upgrade this file or reset the file to the Bootstrap one and apply changes to it since our mindset changed on validation icons.

Apply Bs solution on valid state only. I think that textareas already have a valid state.

### CODE REVIEW

**Review by MewenLeHo — APPROVED** [review]
🆗

**Comment by julien-deramond** [comment]
@louismaximepiton Some conflicts here to resolve 🙏

**Review by julien-deramond — APPROVED** [review]
LGTM! @MewenLeHo I let you double-check the latest modifications before merging it.

@louismaximepiton Could you create an issue to try to reset those files from Bootstrap and apply our modifications on top of it. On top of it, it will help with the "Boosted mod" comments that are off in those files.

**Comment by MewenLeHo** [comment]
> LGTM! @MewenLeHo I let you double-check the latest modifications before merging it.
> 

Looks good but I found two possible problems : 

In responsive, the valid icon goes behind the text:
responsive

If the text written in the textarea is long enough to have a scroll bar then the valid icon goes partially behind it:
screenshot-deploy-preview-1371--boosted netlify app-2022 10 17-09_31_25

**Comment by louismaximepiton** [comment]
> In responsive, the valid icon goes behind the text on small screen:

Resolved by #1306.

> And in desktop, if the text written in the textarea is long enough to have a scroll bar then the valid icon goes partially behind it (may depend of the browser):

Bootstrap seems to have the same issue 🤷 
image

**Pull request merged**
