### PR TITLE
create a dedicated space for essentials

### PR DESCRIPTION
**Pull request by Lausselloic**

### CODE REVIEW

**Comment by Lausselloic** [comment]
@Design-Orange a new section have been created as discuss to put essentials component.
Modules have been moved from examples to essentials as an example
https://deploy-preview-157--boosted.netlify.com/
TODO : 
- define the content of each essentials (title, id description, link)
- maybe define the design of the page?

**Comment by PigeardSylvain** [comment]
I really like that, thanks Loic !
image

**Comment by ffoodd** [comment]
Current status for global headers: 
- [ ] missing mutliple lines / sizes variants for `.navbar-title` (should be done using font-size utilities and grid, I guess);
- [ ] missing a *good* dark search form, related to #117.

**Comment by ffoodd** [comment]
Still missing:
- [ ] mutliple megamenu instances don't seem to work… Or am I doing something wrong?
- [ ] footers (should be easy)
- [ ] search form with suggestions: comobox? datalist? anything else?

**Comment by ffoodd** [comment]
Missing in megamenu:
* [ ] full width sublevel items,
* [ ] should remove dropdown for first level?
* [ ] back button separated from top level label?
* [ ] super nav + language nav respectivly above and beyond megamenu content?
 
To discuss, obviously…

**Comment by ffoodd** [comment]
Managing focus is problematic for now:
* [ ] either we place navbar-toggler after the additionnal menu, meaning we have to handle focus in & out of mega-menu to stay in a consistent tab order;
* [ ] or we duplicate additionnal menu, before and after the megamenu, to be displayed on mobile / desktop view respectively.

Need to give a shot to both solution, to see what's more comfortable to use.

**Comment by ffoodd** [comment]
* [ ] And it's still missing collapsible search forms too.

**Comment by ffoodd** [comment]
Footers are almost done. Only missing:
- [ ] update and check component's documentation for Orange Footer: probably decide to use utility classes or to include styles in component…
- [ ] add a screenshot for the essentials index page

And I think that's it :)

**Comment by ffoodd** [comment]
@Lausselloic @PigeardSylvain FWIW, I think footers are still a work in progress, since I'm considering to create subcomponent for both social nav, services links and sign up form.

It could only consist of awrapper class like `.navbar-social` for example.

But for now it's based on whether we're in footer top/body/bottom, which seems too risky in Boosted.

**Pull request merged**
